modify pipeline to require manual aproval

diff --git a/.github/workflows/pipeline.yml b/.github/workflows/pipeline.yml
--- a/.github/workflows/pipeline.yml
+++ b/.github/workflows/pipeline.yml
@@ -32,6 +32,29 @@ jobs:
           command: npm run test:e2e
           start: npm run start-prod
           wait-on: http://localhost:5001
-      
+
+      - name: Deployment approval
+        if: github.ref == 'refs/heads/main'
+        run: echo "Deployment needs to be manually approved"
+
+  deploy:
+    runs-on: ubuntu-20.04
+    needs: simple_deployment_pipeline
+    environment:
+      name: production
+      url: ${{ secrets.PRODUCTION_URL }}
+    steps:
       - name: Trigger deployment on render
         run: curl https://api.render.com/deploy/${{ secrets.SERVICE_ID }}?key=${{ secrets.RENDER_API_KEY }}
+
+      - name: Verify deployment
+        run: |
+          if curl -s --head  --request GET ${{ secrets.PRODUCTION_URL }} | grep "200 OK" > /dev/null; then
+            echo "Deployment successful"
+          else
+            echo "Deployment failed"
+            exit 1
+          fi
+
+      # - name: Trigger deployment on render
+      #   run: curl https://api.render.com/deploy/${{ secrets.SERVICE_ID }}?key=${{ secrets.RENDER_API_KEY }}
